---
- name: Print mosh version
  debug:
    msg:
      - 'Ansible Version: {{ ansible_play_hosts }}'

- name: Start bot stop
  docker_container:
    name: "gatling-bot{{ emul_prefix | default('') }}"
    state: absent
